name: tests

# This only builds the master branch when it's pushed to, and pull requests
# when they are to master. This avoids double testing prs.
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - uses: cachix/cachix-action@v6
      with:
        name: joprice
    - run: nix-shell --pure --command "make run" ci.nix
